"""
Analysis module for AI Data Analyst Mode.
Handles safe code execution, result capture, and output formatting.
"""
import io
import sys
import traceback
import base64
import textwrap
from contextlib import redirect_stdout, redirect_stderr
from typing import Any, Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")          # non-interactive backend — safe in all environments
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# ── Global plot style ──────────────────────────────────────────────────────────
plt.style.use("seaborn-v0_8-whitegrid")
sns.set_palette("muted")

# ── Constants ──────────────────────────────────────────────────────────────────
_MAX_OUTPUT_CHARS   = 4_000   # truncate captured stdout sent to the AI
_MAX_DF_ROWS        = 50      # max rows stringified per intermediate DataFrame
_SAFE_BUILTINS = {            # minimal __builtins__ for exec — blocks file I/O etc.
    "print": print,
    "range": range,
    "len":   len,
    "list":  list,
    "dict":  dict,
    "set":   set,
    "tuple": tuple,
    "zip":   zip,
    "map":   map,
    "filter": filter,
    "enumerate": enumerate,
    "sorted": sorted,
    "sum":   sum,
    "min":   min,
    "max":   max,
    "abs":   abs,
    "round": round,
    "isinstance": isinstance,
    "type":  type,
    "str":   str,
    "int":   int,
    "float": float,
    "bool":  bool,
    "__import__": __import__,  # needed so exec'd code can import numpy etc.
}


class AnalysisExecutor:
    """
    Executes AI-generated Python code in a controlled namespace and
    captures stdout, result DataFrames, and matplotlib figures.
    """

    def __init__(self, df: pd.DataFrame):
        """
        Initialise the executor with the user's DataFrame.

        Args:
            df: The dataset to expose inside the exec namespace as ``df``.
        """
        self.df = df

    def execute_code(self, code: str) -> Tuple[str, List[Any], List[plt.Figure]]:
        """
        Execute a block of Python code and return all observable side-effects.

        The code is run in an isolated namespace that exposes ``df``, ``pd``,
        ``plt``, ``sns``, and ``np`` (imported on demand).  ``plt.show()`` is
        silenced so figures are captured rather than rendered to a screen.

        Args:
            code: Python source code generated by Gemini.

        Returns:
            ``(output, data_results, figures)`` where:

            - *output* is the captured stdout / stderr as a single string
              (truncated to ``_MAX_OUTPUT_CHARS`` characters).
            - *data_results* is a list of ``{"name", "type", "data"}`` dicts
              for every DataFrame / Series that the code left in local scope.
            - *figures* is a list of every ``matplotlib.figure.Figure``
              created during execution.
        """
        import numpy as np  # imported here so the module itself doesn't require numpy

        # ── Close any lingering figures from a previous run ────────────────────
        plt.close("all")

        namespace: Dict[str, Any] = {
            "df":  self.df.copy(),
            "pd":  pd,
            "plt": plt,
            "sns": sns,
            "np":  np,
        }

        stdout_buf = io.StringIO()
        stderr_buf = io.StringIO()

        # Suppress plt.show so figures are not attempted to be displayed
        _original_show = plt.show
        plt.show = lambda *a, **kw: None

        try:
            with redirect_stdout(stdout_buf), redirect_stderr(stderr_buf):
                namespace["__builtins__"] = __builtins__
                exec(compile(code, "<generated>", "exec"), namespace)
        except Exception:
            stderr_buf.write(traceback.format_exc())
        finally:
            plt.show = _original_show

        # ── Collect output ─────────────────────────────────────────────────────
        combined_output = stdout_buf.getvalue()
        err_text = stderr_buf.getvalue()
        if err_text:
            combined_output += ("\n--- stderr ---\n" + err_text)
        if len(combined_output) > _MAX_OUTPUT_CHARS:
            combined_output = combined_output[:_MAX_OUTPUT_CHARS] + "\n[output truncated]"

        # ── Collect figures ────────────────────────────────────────────────────
        figures: List[plt.Figure] = [
            plt.figure(num) for num in plt.get_fignums()
        ]

        # ── Collect intermediate DataFrames / Series ───────────────────────────
        data_results: List[Dict[str, Any]] = [
            {
                "name": name,
                "type": type(value).__name__,
                "data": value,
            }
            for name, value in namespace.items()
            if isinstance(value, (pd.DataFrame, pd.Series)) and name != "df"
        ]

        return combined_output, data_results, figures

    def plot_to_base64(self, fig: plt.Figure) -> str:
        """
        Encode a matplotlib Figure as a base64 PNG string.

        The figure is closed after encoding to release memory.

        Args:
            fig: The figure to encode.

        Returns:
            Base64-encoded PNG as a UTF-8 string (no data-URI prefix).
        """
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=120, bbox_inches="tight")
        buf.seek(0)
        encoded = base64.b64encode(buf.read()).decode("utf-8")
        plt.close(fig)
        return encoded


class DataAnalyzer:
    """
    High-level interface for running AI-generated analysis steps against a
    DataFrame.  Wraps :class:`AnalysisExecutor` and adds convenience helpers.
    """

    def __init__(self, df: pd.DataFrame):
        """
        Initialise the analyser.

        Args:
            df: The dataset to analyse.
        """
        self.df       = df
        self.executor = AnalysisExecutor(df)

    def run_analysis_step(self, code: str, step_name: str) -> Dict[str, Any]:
        """
        Execute one analysis step and package the results.

        Args:
            code:      Python code generated for this step.
            step_name: Human-readable description of the step (used as a label
                       in the returned dict and in formatted output).

        Returns:
            Dictionary with keys:
            ``step_name``, ``code``, ``output``, ``data_results``,
            ``figures``, ``success``.
        """
        output, data_results, figures = self.executor.execute_code(code)

        # Consider the step successful if no traceback appears in output
        succeeded = "Traceback" not in output and "Error" not in output

        return {
            "step_name":    step_name,
            "code":         code,
            "output":       output,
            "data_results": data_results,
            "figures":      figures,
            "success":      succeeded,
        }

    def run_full_analysis(
        self,
        analysis_steps: List[str],
        code_list: List[str],
    ) -> List[Dict[str, Any]]:
        """
        Execute a sequence of analysis steps.

        Steps are run in order; each step shares the same underlying DataFrame
        (via a copy inside the executor) so they are independent.

        Args:
            analysis_steps: Ordered list of step descriptions.
            code_list:      Corresponding list of Python code strings.

        Returns:
            List of result dicts, one per step (same order as input).
        """
        return [
            self.run_analysis_step(code, step)
            for step, code in zip(analysis_steps, code_list)
        ]

    def generate_summary_statistics(self) -> Dict[str, Any]:
        """
        Compute a structured statistical profile of the dataset.

        Returns:
            Dictionary with keys:
            ``shape``, ``dtypes``, ``missing_values``,
            ``numeric_summary``, ``categorical_summary``.
        """
        df = self.df

        numeric_cols = df.select_dtypes(include="number").columns
        cat_cols     = df.select_dtypes(include=["object", "category"]).columns

        cat_summary: Dict[str, Any] = {}
        for col in cat_cols:
            vc = df[col].value_counts()
            cat_summary[col] = {
                "unique_values": int(df[col].nunique()),
                "top_values":    vc.head(5).to_dict(),
                "missing":       int(df[col].isnull().sum()),
            }

        return {
            "shape":               df.shape,
            "dtypes":              df.dtypes.astype(str).to_dict(),
            "missing_values":      df.isnull().sum().to_dict(),
            "numeric_summary":     (
                df[numeric_cols].describe().round(4).to_dict()
                if len(numeric_cols) else {}
            ),
            "categorical_summary": cat_summary,
        }

    def get_data_preview(self, n: int = 5) -> pd.DataFrame:
        """
        Return the first *n* rows of the dataset.

        Args:
            n: Number of rows (default 5).

        Returns:
            DataFrame slice.
        """
        return self.df.head(n)

    def get_column_distribution(self, column: str) -> Dict[str, Any]:
        """
        Produce a distribution profile for a single column.

        For numeric columns this includes mean, median, std, min, max, and
        the inter-quartile range.  For categorical columns it returns the top
        10 value counts and the percentage of the most-common value.

        Args:
            column: Column name to profile.

        Returns:
            Dictionary of distribution statistics, or ``{"error": "…"}``
            if the column doesn't exist.
        """
        if column not in self.df.columns:
            return {"error": f"Column '{column}' not found in dataset."}

        col  = self.df[column]
        info: Dict[str, Any] = {
            "column":  column,
            "dtype":   str(col.dtype),
            "missing": int(col.isnull().sum()),
            "unique":  int(col.nunique()),
        }

        if pd.api.types.is_numeric_dtype(col):
            q1, q3 = col.quantile(0.25), col.quantile(0.75)
            info.update({
                "mean":   round(float(col.mean()),   4),
                "median": round(float(col.median()), 4),
                "std":    round(float(col.std()),    4),
                "min":    round(float(col.min()),    4),
                "max":    round(float(col.max()),    4),
                "iqr":    round(float(q3 - q1),      4),
            })
        else:
            vc = col.value_counts()
            top_pct = round(vc.iloc[0] / len(col) * 100, 1) if len(vc) else 0
            info["top_values"]      = vc.head(10).to_dict()
            info["top_value_pct"]   = top_pct

        return info


# ── Module-level utility ───────────────────────────────────────────────────────

def format_analysis_results(results: List[Dict[str, Any]]) -> str:
    """
    Render a list of step-result dicts into a plain-text summary for the AI.

    Only includes textual output and stringified DataFrames — figures are
    omitted since they cannot be embedded in a text prompt.

    Args:
        results: List of dicts as returned by :meth:`DataAnalyzer.run_analysis_step`.

    Returns:
        Multi-section plain-text string, one section per step.
    """
    sections: List[str] = []

    for i, result in enumerate(results, 1):
        step_label = result.get("step_name", f"Step {i}")
        status     = "✓" if result.get("success") else "✗ ERROR"
        header     = f"[{i}] {step_label}  {status}"

        parts: List[str] = [header, "─" * len(header)]

        output = (result.get("output") or "").strip()
        if output:
            parts.append(output)

        for dr in result.get("data_results", []):
            name  = dr.get("name", "result")
            dtype = dr.get("type", "")
            data  = dr.get("data")

            parts.append(f"\n{name} ({dtype}):")
            if isinstance(data, pd.DataFrame):
                parts.append(
                    data.head(_MAX_DF_ROWS).to_string(max_colwidth=40)
                )
                if len(data) > _MAX_DF_ROWS:
                    parts.append(f"… {len(data) - _MAX_DF_ROWS} more rows not shown")
            elif isinstance(data, pd.Series):
                parts.append(data.head(_MAX_DF_ROWS).to_string())

        sections.append("\n".join(parts))

    return "\n\n".join(sections)